#!/bin/sh

set -e

cleanup() {
  kind delete cluster
}

# Launching Docker in background
dockerd \
  --host=unix:///var/run/docker.sock \
  --host=tcp://0.0.0.0:$DOCKERD_PORT \
  --mtu 1400 &

# Running confd
confd -onetime -backend env

kind create cluster --config=/tmp/cluster.yaml --loglevel=$KIND_LOGLEVEL --image=$KIND_IMAGE

trap cleanup EXIT

while true
do
  sleep 15 &
  wait
done
