#!/bin/sh

set -e

# Launching Docker in background
dockerd \
  --host=unix:///var/run/docker.sock \
  --host=tcp://0.0.0.0:2375 \
  --mtu 1400 &

# Running confd
confd -onetime -backend env

kind create cluster --config=/tmp/cluster.yaml

while true; do
  sleep 2
done

